### ISSUE TITLE
Directory in Helper file

### ISSUE THREAD

**Issue by ratcliffanastasia** [devsnels/Final_Project#1]
Hi Ya'll, 
So I know that everyone but Devin was having difficulty getting the Shinny App to work. From my understanding, we are having the app pop up but then it disappears immediately. I think this has to do with the relative path file in the helper file which we are feeding through to the Shinny app. I am working to resolve this

**Comment by anakvm** [comment]
Hi all!, I can't run the app. Is someone else still having the same issue (I noticed the code was changed twice)? I was wondering if in my case might be due to the Spanish setting on my laptop.
