### ISSUE TITLE
filter down to southern California counties

### ISSUE THREAD

**Issue by devsnels** [devsnels/Final_Project#2]

**Comment by anakvm** [comment]
Done! In addition, I filtered the cases by the years we are using for the project. I notice we had cases until 2018 (it reduced quite a bit)

**Comment by ratcliffanastasia** [comment]
Anna, did you commit and push this change?

**Comment by anakvm** [comment]
yes, it's in the last chunk (RMarkdown)

**Comment by ratcliffanastasia** [comment]
Got it! So, something that I haven't seen before that's giving me trouble is the <<<<<<<Head and the ====== in the code, can you explain this?

**Comment by ratcliffanastasia** [comment]
in the clean_data file

**Comment by anakvm** [comment]
not sure what you are trying to say. The code was pretty straightforward. 
filter(county %in% c("Imperial" , "Kern", "Los Angeles", "Orange",
                       "Riverside", "San Bernardino", "San Diego", 
                       "San Luis Obispo", "Santa Barbara", "Ventura"))
and head(ca_county cases)

**Comment by ratcliffanastasia** [comment]
No worries! I got it clean up in the clean_data file. 
The R markdown was golden! Just the additions on the clean_data script were super odd so I just make them reflective of the R markdown.

**Comment by anakvm** [comment]
Great! I worked more in the R markdown. But very strange you see the clean_data different. It was the same code.
I changed the name of 1 object to make it more representative of the data. Maybe that affected some parts in the clean_data file??!!
