### ISSUE TITLE
create shiny oi link and username

### ISSUE THREAD

**Issue by devsnels** [devsnels/Final_Project#5]

**Comment by ratcliffanastasia** [comment]
@devsnels @anakvm @erlandso 
Hi all, so I have created an io account. However, the app can't run and it keeps disconnecting. The suggest problem is that the directory for my app isn't clear. 
The warning that I get is attached to this message or in the next. I believe if is talking about how the app directory needs to be the same as the directory for the project....or it has to do with the format of that data set we are reading in at the beginning of the help file.....

I've been playing around for a while and am out of creative options. If someone else has some creative ideas or input....i'd greatly appreciate it

**Comment by ratcliffanastasia** [comment]
![screen shot 2018-12-05 at 10 27 53 pm](https://user-images.githubusercontent.com/44422625/49564317-52c7f900-f8e0-11e8-991b-61fd1ee05641.png)

**Comment by anakvm** [comment]
To set the account did you use your personal information? to try to push Shiny to IO, should we create a new account?. I'm not totally sure I can do it successfully (because the path in helper.R is not working for me). Although, I can try
