### ISSUE TITLE
PDF showing  loading percentages

### ISSUE THREAD

**Issue by anakvm** [devsnels/Final_Project#9]
I just rendered the PDF. But before the last chunk, there're several lines with percentages. Someone knows a trick to delete that? I committed it, to have a reference.

**Comment by ratcliffanastasia** [comment]
are you currently in the document?

**Comment by ratcliffanastasia** [comment]
Where are the percentages coming from??? It looks odd but I'm not sure where it's being generated from.
Have you tried any of the local settings for R mark-down?

**Comment by anakvm** [comment]
From the last chunk I think is related with the geography of the counties. Ans I'm not in the document (trying to do not overlap with you haha)

**Comment by anakvm** [comment]
Fixed!
